#!/usr/bin/env python
# This code extracts the phonon DOS information from total_dos.dat generated by Phonopy code
# It then finds the last two peaks in DOS so that the frequency at which those peaks occured 
# are assumed to be longitudinal optiocal (LO) and transverse optical (TO) phonon frequencies
# Please contact alireza@wustl.edu if you had any questions. Bug reports are very much appreciated.
# By: Alireza Faghaninia

import argparse

def find_DOS_peaks(DOS_filename):
	w_TO = None
	res = []
	dos = list()
	with open(DOS_filename) as data:
	        for line in data:
	                dos.append(line.split())
        dum = -100.0
        index = -1
        counter = 0
        for row in dos[:0:-1]:
                index += 1
                if float(row[1]) >= dum:
                        dum = float(row[1])
			peak = 0
                elif (peak == 0):
                        dum = float(row[1])
			res.append(dos[:0:-1][index-1])
                        counter += 1
			peak = 1
		else:
			dum = float(row[1])
	w_LO = float(res[0][0])
	res = sorted(res,key=lambda x:float(x[1]),reverse=True)
	splitter = 1
	while w_TO is None:
		splitter += 1
		for i in res:
			if (float(i[0]) < w_LO) & (float(i[0]) > w_LO/splitter):
				w_TO = float(i[0])
				break
	return w_LO, w_TO

if __name__ == "__main__":
### Check the input arguments
	parser = argparse.ArgumentParser()
	parser.add_argument("-f","--DOS_file", help="The name of the phonon density of states file", required = True)
	#parser.add_argument("-o","--output_file", help="Results are printed to this file (if the name is provided)", required = False)
	args = parser.parse_args()

### Test the function
	w_LO, w_TO = find_DOS_peaks(args.DOS_file)
	print(w_LO)
	print(w_TO)
